export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          is_admin: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          is_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          is_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          image_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      site_banners: {
        Row: {
          id: string;
          title: string | null;
          message: string;
          is_active: boolean;
          start_date: string | null;
          end_date: string | null;
          variant: 'info' | 'warning' | 'success';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title?: string | null;
          message: string;
          is_active?: boolean;
          start_date?: string | null;
          end_date?: string | null;
          variant?: 'info' | 'warning' | 'success';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string | null;
          message?: string;
          is_active?: boolean;
          start_date?: string | null;
          end_date?: string | null;
          variant?: 'info' | 'warning' | 'success';
          created_at?: string;
          updated_at?: string;
        };
      };
      products: {
        Row: {
          id: string;
          category_id: string | null;
          name: string;
          slug: string;
          description: string | null;
          price: number;
          compare_at_price: number | null;
          stock: number;
          image_url: string | null;
          images: string[] | null;
          is_featured: boolean;
          is_active: boolean;
          metadata: Record<string, any>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          category_id?: string | null;
          name: string;
          slug: string;
          description?: string | null;
          price: number;
          compare_at_price?: number | null;
          stock?: number;
          image_url?: string | null;
          images?: string[] | null;
          is_featured?: boolean;
          is_active?: boolean;
          metadata?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          category_id?: string | null;
          name?: string;
          slug?: string;
          description?: string | null;
          price?: number;
          compare_at_price?: number | null;
          stock?: number;
          image_url?: string | null;
          images?: string[] | null;
          is_featured?: boolean;
          is_active?: boolean;
          metadata?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          user_id: string | null;
          email: string;
          full_name: string;
          phone: string | null;
          shipping_address_line1: string;
          shipping_address_line2: string | null;
          shipping_city: string;
          shipping_postal_code: string;
          shipping_country: string;
          subtotal: number;
          shipping_cost: number;
          tax: number;
          total: number;
          stripe_payment_intent_id: string | null;
          stripe_checkout_session_id: string | null;
          payment_status: 'pending' | 'processing' | 'paid' | 'failed' | 'refunded';
          fulfillment_status: 'unfulfilled' | 'fulfilled' | 'shipped' | 'delivered' | 'cancelled';
          tracking_number: string | null;
          tracking_url: string | null;
          notes: string | null;
          metadata: Record<string, any>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          email: string;
          full_name: string;
          phone?: string | null;
          shipping_address_line1: string;
          shipping_address_line2?: string | null;
          shipping_city: string;
          shipping_postal_code: string;
          shipping_country?: string;
          subtotal: number;
          shipping_cost?: number;
          tax?: number;
          total: number;
          stripe_payment_intent_id?: string | null;
          stripe_checkout_session_id?: string | null;
          payment_status?: 'pending' | 'processing' | 'paid' | 'failed' | 'refunded';
          fulfillment_status?: 'unfulfilled' | 'fulfilled' | 'shipped' | 'delivered' | 'cancelled';
          tracking_number?: string | null;
          tracking_url?: string | null;
          notes?: string | null;
          metadata?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          email?: string;
          full_name?: string;
          phone?: string | null;
          shipping_address_line1?: string;
          shipping_address_line2?: string | null;
          shipping_city?: string;
          shipping_postal_code?: string;
          shipping_country?: string;
          subtotal?: number;
          shipping_cost?: number;
          tax?: number;
          total?: number;
          stripe_payment_intent_id?: string | null;
          stripe_checkout_session_id?: string | null;
          payment_status?: 'pending' | 'processing' | 'paid' | 'failed' | 'refunded';
          fulfillment_status?: 'unfulfilled' | 'fulfilled' | 'shipped' | 'delivered' | 'cancelled';
          tracking_number?: string | null;
          tracking_url?: string | null;
          notes?: string | null;
          metadata?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string | null;
          product_name: string;
          product_image_url: string | null;
          quantity: number;
          unit_price: number;
          total_price: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          product_id?: string | null;
          product_name: string;
          product_image_url?: string | null;
          quantity: number;
          unit_price: number;
          total_price: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          product_id?: string | null;
          product_name?: string;
          product_image_url?: string | null;
          quantity?: number;
          unit_price?: number;
          total_price?: number;
          created_at?: string;
        };
      };
      occasions: {
        Row: {
          id: string;
          brand: string;
          model: string;
          year: number;
          price: number;
          status: 'available' | 'reserved' | 'sold';
          is_active: boolean;
          mileage: number;
          transmission: string;
          fuel: string;
          power: string;
          color: string | null;
          category: string | null;
          specs: Record<string, any>;
          condition: string | null;
          owners: number | null;
          service_history: string | null;
          warranty: string | null;
          features: string[];
          extras: string[];
          description: string | null;
          images: string[];
          main_image: string | null;
          slug: string;
          meta_description: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          woo_product_id: number | null;
          manual_overrides: string[];
        };
        Insert: {
          id?: string;
          brand: string;
          model: string;
          year: number;
          price: number;
          status?: 'available' | 'reserved' | 'sold';
          is_active?: boolean;
          mileage: number;
          transmission: string;
          fuel: string;
          power: string;
          color?: string | null;
          category?: string | null;
          specs?: Record<string, any>;
          condition?: string | null;
          owners?: number | null;
          service_history?: string | null;
          warranty?: string | null;
          features?: string[];
          extras?: string[];
          description?: string | null;
          images?: string[];
          main_image?: string | null;
          slug: string;
          meta_description?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          woo_product_id?: number | null;
          manual_overrides?: string[];
        };
        Update: {
          id?: string;
          brand?: string;
          model?: string;
          year?: number;
          price?: number;
          status?: 'available' | 'reserved' | 'sold';
          is_active?: boolean;
          mileage?: number;
          transmission?: string;
          fuel?: string;
          power?: string;
          color?: string | null;
          category?: string | null;
          specs?: Record<string, any>;
          condition?: string | null;
          owners?: number | null;
          service_history?: string | null;
          warranty?: string | null;
          features?: string[];
          extras?: string[];
          description?: string | null;
          images?: string[];
          main_image?: string | null;
          slug?: string;
          meta_description?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
          woo_product_id?: number | null;
          manual_overrides?: string[];
        };
      };
      page_views: {
        Row: {
          id: string;
          page_path: string;
          page_title: string | null;
          referrer: string | null;
          user_agent: string | null;
          ip_address: string | null;
          country: string | null;
          device_type: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          page_path: string;
          page_title?: string | null;
          referrer?: string | null;
          user_agent?: string | null;
          ip_address?: string | null;
          country?: string | null;
          device_type?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          page_path?: string;
          page_title?: string | null;
          referrer?: string | null;
          user_agent?: string | null;
          ip_address?: string | null;
          country?: string | null;
          device_type?: string | null;
          created_at?: string;
        };
      };
      analytics_events: {
        Row: {
          id: string;
          event_name: string;
          event_data: Record<string, any> | null;
          page_path: string | null;
          user_agent: string | null;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_name: string;
          event_data?: Record<string, any> | null;
          page_path?: string | null;
          user_agent?: string | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_name?: string;
          event_data?: Record<string, any> | null;
          page_path?: string | null;
          user_agent?: string | null;
          ip_address?: string | null;
          created_at?: string;
        };
      };
      occasion_views: {
        Row: {
          id: string;
          occasion_id: string;
          user_agent: string | null;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          occasion_id: string;
          user_agent?: string | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          occasion_id?: string;
          user_agent?: string | null;
          ip_address?: string | null;
          created_at?: string;
        };
      };
    };
  };
}

export type Profile = Database['public']['Tables']['profiles']['Row'];
export type Category = Database['public']['Tables']['categories']['Row'];
export type Product = Database['public']['Tables']['products']['Row'];
export type Order = Database['public']['Tables']['orders']['Row'];
export type OrderItem = Database['public']['Tables']['order_items']['Row'];
export type Occasion = Database['public']['Tables']['occasions']['Row'];
export type OccasionInsert = Database['public']['Tables']['occasions']['Insert'];
export type OccasionUpdate = Database['public']['Tables']['occasions']['Update'];
export type PageView = Database['public']['Tables']['page_views']['Row'];
export type AnalyticsEvent = Database['public']['Tables']['analytics_events']['Row'];
export type OccasionView = Database['public']['Tables']['occasion_views']['Row'];
export type SiteBanner = Database['public']['Tables']['site_banners']['Row'];
export type SiteBannerInsert = Database['public']['Tables']['site_banners']['Insert'];
export type SiteBannerUpdate = Database['public']['Tables']['site_banners']['Update'];
